### ISSUE TITLE
[Bug] 是不是没有帮装python3.8

### ISSUE THREAD

**Issue by herrywen-nanj** [jumpserver/installer#103]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  镜像里的python版本不是python3.8然后报错了
2. ![image](https://user-images.githubusercontent.com/33476935/123049066-b6c85380-d431-11eb-9d1e-7544bcb2f59c.png)

3.安装后报错
![image](https://user-images.githubusercontent.com/33476935/123049097-c5166f80-d431-11eb-8e29-9fb7ed766d51.png)

**Comment by bob-taotao** [comment]
请问这个问题解决了吗？ 我今天也有遇到。

**Comment by herrywen-nanj** [comment]
换了v2.5.3的安装脚本就好了
