### ISSUE TITLE
[Feature] jmsctl 执行文件 建议

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/installer#116]
**请描述您的需求或者改进建议.**
你好，近期使用了 DataEase，发现部署完成后会生成 dectl 可执行文件；
我们JumpServer是否也可以借鉴下，这样就不需要在安装工具目录下去使用这个脚本了；
对用户体验感好
![image](https://user-images.githubusercontent.com/58923704/125546360-9fb32b4d-159b-4e62-9565-526ce93c00ae.png)

**Comment by wojiushixiaobai** [comment]
可以用 alias 来做
```sh
alias jmsctl=/opt/jumpserver-installer-v2.12.0/jmsctl.sh
```
完整代码
```sh
cat jmsctl.sh
```
```sh
function pre_check() {
  check_config_file || return 3
  if [[ "${SHELL}" == "/bin/bash" ]]; then
    if ! grep -q "alias jmsctl=" ~/.bashrc; then
      echo 'alias jmsctl="'${PROJECT_DIR}'/jmsctl.sh"' >> ~/.bashrc
    else
      sed -i 's@alias jmsctl=.*@alias jmsctl="'${PROJECT_DIR}'/jmsctl.sh"@g' ~/.bashrc
    fi
  fi
}
```

**Comment by luweijun1992** [comment]
> 可以用 alias 来做
> 
> ```shell
> alias jmsctl="cd /opt/jumpserver-installer-v2.12.0 && ./jmsctl.sh"
> ```
> 
> 完整代码
> 
> ```shell
> cat jmsctl.sh
> ```
> 
> ```shell
> function pre_check() {
>   check_config_file || return 3
> 
>   if [[ "${SHELL}" == "/bin/bash" ]]; then
>     if grep -q "alias jmsctl=" ~/.bashrc; then
>       sed -i 's@alias jmsctl=$@alias jmsctl="cd '${PROJECT_DIR}' && ./jmsctl.sh"@g' ~/.bashrc
>     else
>       echo 'alias jmsctl="cd '${PROJECT_DIR}' && ./jmsctl.sh"' >> ~/.bashrc
>     fi
>   fi
> }
> ```
> 
> 执行一条命令，更新 alias 命令至 ~/.bashrc
> 
> ```shell
> ./jmsctl.sh status
> ```
> 
> 下次登录就能使用 jmsctl 来管理了
> 
> ```shell
> jmsctl --help
> ```

建议可以在install部署完环境后自动做这个步骤。方便用户使用
