### ISSUE TITLE
[Bug] 从v2.13.2升级到v2.14.1失败

### ISSUE THREAD

**Issue by vzrs** [jumpserver/installer#164]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.14.1

**浏览器版本**
Edge

**Bug 描述**
从v2.13.2升级到v2.14.1失败，报错“[ERROR] 表结构变更失败!”，错误信息：（1050, "Table 'tickets_approvalrule_assignees' already exists"）和（1050, "Table 'tickets_approvalrule' already exists"）。

**Bug 重现步骤(有截图更好)**
1.  执行./jmsctl.sh upgrade，进行到数据库更新，提示错误（1050, "Table 'tickets_approvalrule_assignees' already exists"）。
2.  再次执行./jmsctl.sh upgrade，进行到数据库更新，提示错误（1050, "Table 'tickets_approvalrule' already exists"）。
3.  之后再./jmsctl.sh upgrade都是（1050, "Table 'tickets_approvalrule' already exists"），也无法启动。

注：之前从v2.6.x和v2.10.x升级到v2.13.x时，进行到数据库更新一步都会出现类似表已存在的错误，但重复执行若干次最终可升级并启动成功。

**Comment by wojiushixiaobai** [comment]
字符集可能有问题，检查下
