### ISSUE TITLE
[Bug] 终端连接和退出linux服务器 都要停顿10秒左右

### ISSUE THREAD

**Issue by mufengit** [jumpserver/installer#182]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
chrome 97.0.4692.71

**Bug 描述**
终端连接和退出linux服务器 都要停顿10秒左右，
填写的资产记录和用户组大概1千多。

以下两个版本都是
Version v2.11.0 GPLv2. ~ Version v2.17.3 GPLv2.  

**Bug 重现步骤(有截图更好)**
1.  
2.
3.

**Comment by wojiushixiaobai** [comment]
看下接口，具体是哪个接口响应慢

**Comment by wojiushixiaobai** [comment]
浏览器开发者工具栏确定

**Comment by mufengit** [comment]
新安装的jumpserver，加几条记录，登入很快。把现有数据库导进去就很慢

**Comment by wojiushixiaobai** [comment]
数据量太大？可以尝试优化下数据库配置

**Comment by mufengit** [comment]
数据库没任何压力，我觉得是产品问题

**Comment by wojiushixiaobai** [comment]
你是否配置了 docker ipv6？

**Comment by mufengit** [comment]
这些因素都没有，为什么单台资源的时候连接不慢，把所有资源库导进去就慢了呢

**Comment by mufengit** [comment]
这些因素都没有，为什么测试时候只添加单个服务器记录，连接的时候连接不慢，把所有资源库导进去就慢了呢

**Comment by wojiushixiaobai** [comment]
无法复现，请自行解决

**Comment by RainNameless** [comment]
> 这些因素都没有，为什么测试时候只添加单个服务器记录，连接的时候连接不慢，把所有资源库导进去就慢了呢

有点好奇 mysql装在哪？ 外用的mysql 还是同一台服务器上的？redis呢？ 如果有外用的请自行排查 jumpserver其实算是很轻量的web 相信处理的数据量也不会太大吧  卡顿能想象只能是数据响应问题  还有是否做了域名加cdn？
排除完以上如果还是卡建议直接从web页面导出所有csv数据  新搭建一个 从页面用csv导入数据

**Comment by RainNameless** [comment]
> 无法复现，请自行解决

我也发现了这个问题   因为昨天出现了批量命令只显示1行资产列表  今天新搭v2.19.1  打开果然很忙 果断用无痕模式清除缓存对比 发现了datatables.min.js 要拉取14s = =
第一张为v2.19.1
![image](https://user-images.githubusercontent.com/43627188/155273420-be40ade8-dad7-48b3-a0f2-e48d2c300451.png)

![image](https://user-images.githubusercontent.com/43627188/155273605-e7dd6a7f-a675-45a1-8a1b-fd5adcb4a4c7.png)
