### ISSUE TITLE
jumpserver1.6 

### ISSUE THREAD

**Issue by RainNameless** [jumpserver/installer#190]
jumpserver1.6版本  安装异常删容器 = =  还有容器镜像  还好有持久化 不然数据都没了

static.env 指定镜像版本有问题 有些附属应用容器没有那个版本

jumpserver2.19资源列表添加过多后 在命令批量管理只能显示出一行

还有请教一个问题 密钥链接的linux 怎么样提取硬件资源？

**Comment by wojiushixiaobai** [comment]
第三个问题截图看看
第四个问题提取硬件资源是啥意思？页面的获取硬件信息？

**Comment by RainNameless** [comment]
![image](https://user-images.githubusercontent.com/43627188/155164040-b1a1ebbc-5dc2-4505-b249-e35403ee3ff4.png)
![image](https://user-images.githubusercontent.com/43627188/155164198-227e37d8-9fcc-4ff7-9622-c4d78a6e7b28.png)

第四个问题 是节点不是有个自动探测可以更新硬件信息吗？  我用密码的话就成功了 密钥获取失败了  不知道密钥要怎么操作
