### ISSUE TITLE
[Bug]  最新版 v2.22.0 执行./jms upgrade的时候报错

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/installer#220]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
2.22.0脚本升级报错

**Bug 重现步骤(有截图更好)**
1.  下载官方最新的jumpserver-installer-v2.22.0
2. 执行./jmsctl.sh  upgrade
3.产生如图报错
![image](https://user-images.githubusercontent.com/81400245/169657641-161cbe35-3428-4571-b987-771f1388f377.png)

**Comment by wojiushixiaobai** [comment]
无法复现，请检查环境是否有问题
