### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/installer#298]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-installer-v2.28.7升级到jumpserver-installer-v3.0.1
**浏览器版本**
版本 110.0.1587.57 (正式版本) (64 位)
**Bug 描述**
升级后ssh配置到远端的密钥验证无法使用
**Bug 重现步骤(有截图更好)**
V2.28.7是正常的如下
![image](https://user-images.githubusercontent.com/70053869/221599798-56f42f69-78a0-40ce-af10-7b6672717a3b.png)
v3.0.1升级后不正常如下
![image](https://user-images.githubusercontent.com/70053869/221600112-285cafed-5fa2-4505-8825-7b53fca2f05f.png)

**Comment by ibuler** [comment]
去资产详情中/账号 中看看对不对

**Comment by JeongHyeokLee** [comment]
v2.28.7一切正常 升级到 v3.0.1 就这样了 之前升级都是正常的

**Comment by ibuler** [comment]
那先关掉了
