### ISSUE TITLE
[Feature] 输出当前版本和升级提示

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/installer#32]
**请描述您的需求或者改进建议.**
用check_update校验升级时，如果当前已经是最新，就输出最新提示，后面加个当前版本
用upgrade升级版本时，如果当前版本是最新版本，就输出最新提示，然后加上当前版本 然后再提示是否继续升级
如果可以，后续加个降级脚本

**Comment by luweijun1992** [comment]
是否增加个卸载参数呢？
还有就是jmsctl.sh 脚本没有同步拷贝到/opt/jumpserver 目录进行后续维护使用吗？还得到/opt/jumpserver-install目录下进行操作。

**Comment by ibuler** [comment]
已添加

```
./jmsctl.sh check_update
当前版本已是最新: v2.6.2
```

**Comment by ibuler** [comment]
@luweijun1992 卸载直接删掉 /opt/jumpserver /opt/docker 就行
