### ISSUE TITLE
[Feature] 使用外置数据库pull image判断优化

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/installer#33]
**请描述您的需求或者改进建议.**
在使用jmsctl.sh install 时候使用外置数据库，但是在拉取镜像的时候还是会把mysql数据库拉到本地；是否可以做下判断，当使用外置数据库时候不拉去image到本地。
1.节省pull mysql镜像时间，加快安装用时。

**Comment by ibuler** [comment]
备份数据库需要 MySQL 镜像
