### ISSUE TITLE
[Bug] 离线安装时遇到问题

### ISSUE THREAD

**Issue by Chasii** [jumpserver/installer#37]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.6.1
**浏览器版本**

**Bug 描述**

ERROR: for jms_mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:348: starting conner process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/opt/jumpserveonfig/mysql/my.cnf\\\" to rootfs \\\"/opt/docker/overlay2/e81902f00772a46a4fab0a4d3c0257e18798c2ca618af02a564b8f42c99a5/merged\\\" at \\\"/opt/docker/overlay2/e81902f00772a46a4fab0a4d3c0257e18798c2ca618af02a564b8f4ebd2c99a5/me
Creating jms_redis ... donee (or vice-versa)? Check if the specified host path exists and is the expected type
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by currycan** [comment]
配置文件没有挂载,这个是 docker 的基本报错,自己好好查查

**Comment by ibuler** [comment]
ls /opt/jumpserveonfig/mysql/my.cnf

**Comment by Chas-IO** [comment]
所有的/opt/jumpserver/config文件夹下的配置文件都变成了文件夹。。。不知道是不是安装脚本有什么问题
环境：CentOS Linux release 7.3.1611 (Core)

**Comment by yuanhaoliang** [comment]
> 所有的/opt/jumpserver/config文件夹下的配置文件都变成了文件夹。。。不知道是不是安装脚本有什么问题
> 环境：CentOS Linux release 7.3.1611 (Core)
> Server Version: 18.06.2-ce

我也遇到这个问题！

Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:16:13 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker-compose version 1.28.2, build unknown
docker-py version: 4.4.1
CPython version: 3.6.1
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by yuanhaoliang** [comment]
> 所有的/opt/jumpserver/config文件夹下的配置文件都变成了文件夹。。。不知道是不是安装脚本有什么问题
> 环境：CentOS Linux release 7.3.1611 (Core)
> Server Version: 18.06.2-ce

我找到原因了，是因为初始化时，没能把config_init复制到/opt/jumpserver/config下面去。如果/opt/jumpserver/config存在的话，就不会执行这个操作了。

**Comment by Chas-IO** [comment]
> > 所有的/opt/jumpserver/config文件夹下的配置文件都变成了文件夹。。。不知道是不是安装脚本有什么问题
> > 环境：CentOS Linux release 7.3.1611 (Core)
> > Server Version: 18.06.2-ce
> 
> 我找到原因了，是因为初始化时，没能把config_init复制到/opt/jumpserver/config下面去。如果/opt/jumpserver/config存在的话，就不会执行这个操作了。

我是安装之前手动复制这个文件下所有的配置文件过去，才勉强安装成功。

**Comment by RuioWolf** [comment]
> > 所有的/opt/jumpserver/config文件夹下的配置文件都变成了文件夹。。。不知道是不是安装脚本有什么问题
> > 环境：CentOS Linux release 7.3.1611 (Core)
> > Server Version: 18.06.2-ce
> 
> 我也遇到这个问题！ @ibuler
> 我还遇到了docker-compose不读.env文件的问题。
> 即使我手动export CONFIG_FILE CONFIG_DIR VERSOIN等几个变量，手动执行docker-compose，最终/opt/jumpserver/config文件夹下的配置文件都变成了文件夹
> 
> ```shell
> docker-compose -f ./compose/docker-compose-app.yml -f compose/docker-compose-network.yml -f ./compose/docker-compose-task.yml -f ./compose/docker-compose-mysql.yml -f ./compose/docker-compose-redis.yml --env-file /opt/jumpserver/config/config.txt up -d
> ```
> 
> ```
> docker version
> 
> Client: Docker Engine - Community
>  Version:           20.10.2
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        2291f61
>  Built:             Mon Dec 28 16:17:48 2020
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.2
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       8891c58
>   Built:            Mon Dec 28 16:16:13 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.3
>   GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
>  runc:
>   Version:          1.0.0-rc92
>   GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> 
> docker-compose version
> 
> docker-compose version 1.28.2, build unknown
> docker-py version: 4.4.1
> CPython version: 3.6.1
> OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
> ```

我这里也有相同的问题，确认在 `/opt/jumpserver/config/config.txt` 中存在 `HTTP_PORT`, `HTTP_PORT`, `SSH_PORT`, `VOLUME_DIR` 配置，但是启动的时候就会出现这样的提示。

```bash
[root@localhost jmsctl]# ./jmsctl.sh start
WARNING: The HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The HTTPS_PORT variable is not set. Defaulting to a blank string.
WARNING: The VOLUME_DIR variable is not set. Defaulting to a blank string.
WARNING: The SSH_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file '././compose/docker-compose-app.yml' is invalid because:
services.koko.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
```

**Comment by wojiushixiaobai** [comment]
@RuioWolf docker-compose >= 1.28 需要将 .env 拷贝到 compose 目录，目前 docker 官方尚未对此问题进行定义是否属于 bug
我们推荐使用 1.27 版本，可以避免此问题。

如果后续 docker 官方确定不会修改此问题，我们将会在代码中修复 .env 的位置

**Comment by LeoHsiao1** [comment]
我今天在新主机上安装 docker-compose==1.29.1 和 Jumpserver==2.9.2 ，也遇到报错说 docker-compose 的语法不正确：
```sh
[root@CentOS /opt/jumpserver-installer-v2.9.2]# sh jmsctl.sh status                                                                                                                                     
ERROR: The Compose file './compose/docker-compose-network.yml' is invalid because:
networks.net.ipam.config.subnet is invalid: should use the CIDR format
```

调试了下，发现是 docker-compose-xx.yml 未导入配置变量，猜测是新版本不兼容。
于是将 Jumpserver 回滚到 2.7 版本，依然报错。又将 docker-compose 回滚到 1.27 版本，报错消失。
