### ISSUE TITLE
[Question] 2.5.3的如何升级到2.6版本

### ISSUE THREAD

**Issue by OPSTime** [jumpserver/installer#45]
2.5.3的如何升级到2.6版本
原来是通过咱们提供的docker-compose.yml方式安装的

**Comment by OPSTime** [comment]
通过这个也能安装2.5.4版本的吗？

**Comment by wojiushixiaobai** [comment]
@OPSTime https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/ 参考升级文档升级
