### ISSUE TITLE
[Feature] 建议已安装好的docker版本大于安装器所需的，就不用处理docker的安装了。

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/installer#57]
我的docker版本已经是20.10.2了，大于安装器所需的，但安装脚本还是要去下载和安装docker，是不需要的。而且还会影响本机的正在运行的其它docker容器。。

**Comment by luweijun1992** [comment]
是的，或者给个版本要求。用户可以提前将docker环境准备好

**Comment by birdofprey** [comment]
离线安装部署很重要。毕竟不是每一个需要用到堡垒机得地方都可以连接互联网。既然自由开源了。还是建议能全自由，方便普及用户群。我觉得只要好总会有很多商业用户愿意出钱买相应得集成化和商业支持服务。但没有更广泛得用户群，商业用户真的很难说！！！

**Comment by wojiushixiaobai** [comment]
@yuanhaoliang @luweijun1992 @birdofprey 已经处理，用户已经安装 docker 和 docker-compose 后将跳过安装

**Comment by luweijun1992** [comment]
> @yuanhaoliang @luweijun1992 @birdofprey 已经处理，用户已经安装 docker 和 docker-compose 后将跳过安装

建议在文档部署资料上将 docker 和 docker-compose 所需版本号要求 标注上。
