### ISSUE TITLE
[Feature] 建议把版本相关的image用docker save导出离线安装包以加速安装

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/installer#58]
docker save -o images.tar jumpserver/luna:v2.7.0 jumpserver/lina:v2.7.0 jumpserver/koko:v2.7.0等等然后发布到release里以便加速安装。不知为啥，用了镜像加速，安装jumpserver的镜像时还是好慢好慢。。

**Comment by luweijun1992** [comment]
或者将改镜像放在国内云端上，方便国内下载。现在放在dockerhub上下载速度太慢了。

**Comment by ibuler** [comment]
没找到合适的能白嫖的源

**Comment by wojiushixiaobai** [comment]
区域 | 镜像仓库地址 | 配置文件 /opt/jumpserver/config/config.txt
华北-北京一 | swr.cn-north-1.myhuaweicloud.com | DOCKER_IMAGE_PREFIX=swr.cn-north-1.myhuaweicloud.com
华北-北京四 | swr.cn-north-4.myhuaweicloud.com | DOCKER_IMAGE_PREFIX=swr.cn-north-4.myhuaweicloud.com
华南-广州     | swr.cn-south-1.myhuaweicloud.com | DOCKER_IMAGE_PREFIX=swr.cn-south-1.myhuaweicloud.com
华东-上海一 | swr.cn-east-3.myhuaweicloud.com    | DOCKER_IMAGE_PREFIX=swr.cn-east-3.myhuaweicloud.com
亚太-香港     | swr.ap-southeast-1.myhuaweicloud.com | DOCKER_IMAGE_PREFIX=swr.ap-southeast-1.myhuaweicloud.com
亚太-新加坡 | swr.ap-southeast-3.myhuaweicloud.com | DOCKER_IMAGE_PREFIX=swr.ap-southeast-3.myhuaweicloud.com
