### ISSUE TITLE
[Bug] 选择外置后仍然拉取 mysql 等镜像

### ISSUE THREAD

**Issue by ihacku** [jumpserver/installer#60]
**JumpServer 版本(v1.5.9以下不再支持)**
2.7

**Bug 描述**
安装时选择使用外置 mysql redis 仍然会拉取 mysql 及 redis docker 镜像

另外

# 可以设置 国内加速源来安装
$ export DOCKER_IMAGE_PREFIX=docker.mirrors.ustc.edu.cn

ustc 的源貌似已经不对外服务了

**Comment by ibuler** [comment]
mysql 备份数据库也使用，加速源改一下
