### ISSUE TITLE
[Feature] 建议把所有脚本里硬编码的/opt/jumpserver路径做成变量

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/installer#62]
const.sh里设定一个用于默认使用的JMS_DEFAULT_DIR=/opt/jumpserver，例如当VOLUME_DIR为空时使用JMS_DEFAULT_DIR。

否则所有都使用VOLUME_DIR变量替代硬编码的/opt/jumpserver

因为整个项目都docker化了，就没必要固定在/opt/jumpserver目录了。一切都只是一个映射而已。

对于我来说，/opt是系统盘，然而应用数据，我会放在数据盘。

**Comment by ibuler** [comment]
配置文件目录 CONFIG_DIR 是固定的，不能变为再 VOLUME_DIR 中的，因为 VOLUME_DIR 在配置文件中写的，鸡生蛋还是蛋生鸡，总得有个开始
