### ISSUE TITLE
[Bug] 按照提示选择docker升级之后，版本没变化

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/installer#64]
**JumpServer 版本(v1.5.9以下不再支持)**
2.7.0

**浏览器版本**

**Bug 描述**

按照提示选择docker升级之后，版本没变化
**Bug 重现步骤(有截图更好)**
1.  升级之前docker版本
![image](https://user-images.githubusercontent.com/44529247/106990954-42598480-67b0-11eb-8a6d-3fd3087d8838.png)

2. 按照提示选择升级docker
![image](https://user-images.githubusercontent.com/44529247/106990977-4be2ec80-67b0-11eb-82d8-2fc1f35633a4.png)

2. 脚本执行完成之后docker版本
![image](https://user-images.githubusercontent.com/44529247/106997626-2bba2a00-67be-11eb-83c3-36a755438f0e.png)

3.

**Comment by wojiushixiaobai** [comment]
./jmsctl.sh restart
如果还是不行 _[参考官方升级文档](https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/)
