### ISSUE TITLE
[Question] 版本2.7.1部署出现的问题

### ISSUE THREAD

**Issue by caoxpgg** [jumpserver/installer#65]
**请描述您的问题.**
部署方式：
export DOCKER_IMAGE_PREFIX=swr.cn-north-1.myhuaweicloud.com
curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.7.1/quick_start.sh | bash

采用内部mysql和redis报错：
[root@whdata jumpserver-installer-v2.7.1]# ./jmsctl.sh restart
ERROR: Named volume "y/redis/data:/data:rw" is used in service "redis" but no declaration was found in the volumes section.
ERROR: Named volume "y/mysql/data:/var/lib/mysql:rw" is used in service "mysql" but no declaration was found in the volumes section.

采用外部mysql和redis报错：
[root@whdata jumpserver-installer-v2.7.1]# ./jmsctl.sh start
ERROR: Named volume "y/core/data:/opt/jumpserver/data:rw" is used in service "core" but no declaration was found in the volumes section.

**Comment by wojiushixiaobai** [comment]
提示有 (y/n) 才需要输入 y或者n，默认请直接回车，不需要输入任何信息
```sh
rm -rf /opt/jumpserver/config
./jmsctl.sh install
```
请重新安装

**Comment by caoxpgg** [comment]
rm -rf /opt/jumpserver/config
./jmsctl.sh install
如上操作后报错：
[root@whdata jumpserver-installer-v2.7.1]# ./jmsctl.sh start
Creating network "jms_net" with driver "bridge"
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-76bc9483fe84 -j RETURN: iptables: No chain/target/match by that name.

docker 启动或创建容器是报 Failed to Setup IP tables: Unable to enable SKIP DNAT rule 错误的的解决办法
1，原因：在对 linux 的防火墙进行操作之后，需要重启 docker
2，解决办法：service docker restart
