### ISSUE TITLE
[Question] docker镜像的Dockerfile在哪里，想定制tls1.3到nginx镜像中

### ISSUE THREAD

**Issue by toimc** [jumpserver/installer#67]
**请描述您的问题.**

我想知道原先的项目https://github.com/jumpserver/Dockerfile 中的那些dockerfile，特别是nginx定制的话，最新的Dockerfile在哪里？

**Comment by wojiushixiaobai** [comment]
@toimc 目前的 Dockerfile 就是仓库自带的 Dockerfile
- [x] [core](https://github.com/jumpserver/jumpserver/blob/master/Dockerfile)
- [x] [koko](https://github.com/jumpserver/koko/blob/master/Dockerfile)
- [x] [guacamole](https://github.com/jumpserver/docker-guacamole/blob/master/Dockerfile)
- [x] [lina](https://github.com/jumpserver/lina/blob/master/Dockerfile)
- [x] [luna](https://github.com/jumpserver/luna/blob/master/Dockerfile)
