### ISSUE TITLE
[Question] 配置文件升级步骤疑问

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/installer#71]
**请描述您的问题.**
现在的产品都是通过docker方式部署，配置文件用的是/opt/jumpserver/config/config.txt；
旧版本安装工具生成该文件，然而跟现有v2.8.x所提供的 config-example.txt 查看是存在差异的；
针对这个配置文件，有什么更新该配置文件的方法步骤吗？
以下为v2.7生成跟现有v2.8提供的example文件对比。
![image](https://user-images.githubusercontent.com/58923704/112403463-6c0f4080-8d49-11eb-8ecd-e0e87677b362.png)

**Comment by wojiushixiaobai** [comment]
@luweijun1992 不一样也不影响使用，或者可以手动更新。看你的需求

**Comment by luweijun1992** [comment]
> @luweijun1992 不一样也不影响使用，或者可以手动更新。看你的需求

就怕新版本新增加一些参数，然而老版本生成的配置文件中并没有这些新参数。
请告知下手动更新的方法步骤，谢谢。

**Comment by wojiushixiaobai** [comment]
手动复制过去即可

**Comment by luweijun1992** [comment]
> 手动复制过去即可

如果我直接使用“config-example.txt”，然后修改里面的参数，最终将这个文件改名覆盖“/opt/jumpserver/config/config.txt”，这个方法应该更合适。
但是发现一个问题，安装工具提供的“config-example.txt”和部署完成后生成的“/opt/jumpserver/config/config.txt”；文件内容还是存在差异的。

**Comment by wojiushixiaobai** [comment]
@luweijun1992 差异的部分可以保持默认
