### ISSUE TITLE
官网提供的安装方式太复杂，重写了docker-compose[Feature] 

### ISSUE THREAD

**Issue by teazj** [jumpserver/installer#72]
**请描述您的需求或者改进建议.**
官网提供的安装方式太复杂，重写了docker-compose ,仓库地址
https://github.com/teazj/jumpserver-v2.8.2-docker-compose.git

**Comment by wojiushixiaobai** [comment]
## 以前提供过类似的安装方式
- [ ] [Dockerfile](https://github.com/jumpserver/Dockerfile)
- [ ] [Dockerfile](https://github.com/wojiushixiaobai/Dockerfile)
## 目前我们推荐使用 installer 来完成部署
- [x] [jumpserver-installer]https://github.com/jumpserver/installer
