### ISSUE TITLE
[Bug] 启动时 .env 中的环境变量无法加载

### ISSUE THREAD

**Issue by tttlkkkl** [jumpserver/installer#74]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.8.2

docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:04 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:27 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
**浏览器版本**

**Bug 描述**
当运行 start 的时候报错，原因是 .env 的软链接需要放在 compose 目录下面才能被 docker-compose 正确加载。
执行 ln -s /opt/jumpserver/config/config.txt compose/.env 可修复次错误。
**Bug 重现步骤(有截图更好)**
1.  手动安装 v2.8.2
2. 执行 start 命令
![image](https://user-images.githubusercontent.com/8353103/114120831-ddd9b380-991f-11eb-95ec-876bd5f8cc0c.png)

**Comment by wojiushixiaobai** [comment]
docker-compose >= 1.28 参数的此问题，目前官方尚未给出是否属于bug的说明
详情请关注 https://github.com/docker/compose/issues 此链接的官方问题说明
推荐降级到 1.27 版本来解决此问题

**Comment by tttlkkkl** [comment]
降级搭配1.27果然没有再报错
