### ISSUE TITLE
[Question]  使用 installer 重启过程遇到 ERRoR

### ISSUE THREAD

**Issue by LizhenQiangCOOL** [jumpserver/installer#77]
**请描述您的问题.**

root@localhost:/opt/jumpserver-installer-v2.8.2 #./jmsctl.sh start
ERROR: Named volume "y/redis/data:/data:rw" is used in service "redis" but no declaration was found in the volumes section.

**Comment by LizhenQiangCOOL** [comment]
> **请描述您的问题.**
> 
> root@localhost:/opt/jumpserver-installer-v2.8.2 #./jmsctl.sh start
> ERROR: Named volume "y/redis/data:/data:rw" is used in service "redis" but no declaration was found in the volumes section.

请问有什么建议吗，目前没有什么好的思路

**Comment by wojiushixiaobai** [comment]
请使用最新的安装脚本，你的路径错误了，
路径不应该为  `y/redis/data` 这不是一个正确的路径，你应该是在操作过程中没有注意看提示导致的结果。请删除 /opt/config/config 目录。然后重新开始
