### ISSUE TITLE
[Bug] sh jmsctl.sh status 

### ISSUE THREAD

**Issue by wahello** [jumpserver/installer#87]
**JumpServer 版本 2.10

**Bug 描述**
执行 `sh jmsctl.sh status  `
```
ERROR: Named volume "y/redis/data:/data:rw" is used in service "redis" but no declaration was found in the volumes section.
```
使用 `docker stop jms_redis`  及  `docker start jms_redis ` 没有这个问题.

**Bug 重现步骤**
1. 之前安装过2.6的版本
2. 现在升级到2.10 
3. 执行 sh jmsctl.sh status

**Comment by wojiushixiaobai** [comment]
`y/redis/data`
这个路径不是正常的路径
修改 `/opt/jumpserver/config/config.txt`
将错误的路径修正
