### ISSUE TITLE
请问在运行cd scripts && bash 0_prepare.sh这个命令后，出现error: invalid filename(should not contain ':') 应该如何解决，谢谢

### ISSUE THREAD

**Issue by JayJQK** [jumpserver/installer#96]
**请描述您的问题.**
请问在运行cd scripts && bash 0_prepare.sh这个命令后，出现error: invalid filename(should not contain ':') 应该如何解决，谢谢

**Comment by wojiushixiaobai** [comment]
请先正常./jmsctl.sh install 后，在执行离线包制作

**Comment by JayJQK** [comment]
已经执行过安装程序，可以正常使用。 还是原问题，应该如何解决，谢谢。

**Comment by wojiushixiaobai** [comment]
https://docs.jumpserver.org/zh/master/about/contact/

https://qm.qq.com/cgi-bin/qm/qr?k=om7dOmqflNsfzegPBODIxooO_dMDGiD1&jump_from=webapi

加到群里面，我远程看下
